<script setup lang="ts">
import { onMounted, ref, reactive } from 'vue'
import type { FormInstance } from 'element-plus'
import { ElMessage } from 'element-plus'
import { api, save } from '../../api/client'
import type { Menu } from '../../api/types'
import RequestError from '../../components/RequestError.vue'
const menus=ref<Menu[]>([]),loading=ref(false),saving=ref(false),error=ref<Error|null>(null),formError=ref(''),dialog=ref(false),selected=ref<Menu>(),form=ref<FormInstance>()
const values=reactive({name:'',icon:'',sortOrder:0,enabled:true})
async function load(){loading.value=true;error.value=null;try{menus.value=await api<Menu[]>('/admin/menus')}catch(e){error.value=e as Error}finally{loading.value=false}}
function edit(menu:Menu){selected.value=menu;Object.assign(values,{name:menu.name,icon:menu.icon??'',sortOrder:menu.sortOrder,enabled:menu.enabled});formError.value='';dialog.value=true}
async function submit(){if(!await form.value?.validate().catch(()=>false)||!selected.value)return;saving.value=true;try{await save(`/admin/menus/${selected.value.id}`,{...values},'PUT');dialog.value=false;ElMessage.success('菜单已更新，下次加载菜单时生效');await load()}catch(e){formError.value=(e as Error).message}finally{saving.value=false}}
onMounted(load)
</script>
<template><div class="page-head"><div><h1>菜单管理</h1><p>调整菜单显示名称、图标、排序和启停状态</p></div></div><RequestError :error="error" @retry="load"/><section class="surface table-panel"><div class="panel-head"><h2>系统菜单</h2><small class="muted">模块自动注册 · 技术字段只读</small></div><el-table v-loading="loading" :data="menus" row-key="id" default-expand-all empty-text="暂无已注册菜单"><el-table-column prop="name" label="菜单名称" min-width="180"/><el-table-column prop="menuCode" label="菜单代码（只读）" min-width="200"/><el-table-column prop="routePath" label="路由（只读）" min-width="180"/><el-table-column prop="componentKey" label="组件（只读）" min-width="160"/><el-table-column prop="icon" label="图标" width="120"/><el-table-column prop="sortOrder" label="排序" align="right" width="80"/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag size="small" :type="row.enabled?'success':'info'">{{ row.enabled?'启用':'停用' }}</el-tag></template></el-table-column><el-table-column label="操作" fixed="right" width="80"><template #default="{row}"><el-button text type="primary" size="small" @click="edit(row)">编辑</el-button></template></el-table-column></el-table></section><el-dialog v-model="dialog" title="编辑菜单" width="580px" destroy-on-close :close-on-click-modal="false"><el-alert v-if="formError" :title="formError" type="error" :closable="false"/><el-form ref="form" :model="values" label-position="top" @submit.prevent="submit"><div class="form-grid"><el-form-item label="菜单名称" prop="name" :rules="[{required:true,message:'请输入菜单名称',trigger:'blur'}]"><el-input v-model="values.name" maxlength="100"/></el-form-item><el-form-item label="图标"><el-select v-model="values.icon" clearable><el-option v-for="icon in ['DataBoard','Upload','User','Key','Menu','Document','Connection']" :key="icon" :value="icon" :label="icon"/></el-select></el-form-item><el-form-item label="排序"><el-input-number v-model="values.sortOrder" :min="0" :max="2147483647" :precision="0"/></el-form-item><el-form-item label="状态"><el-switch v-model="values.enabled" active-text="启用" inactive-text="停用"/></el-form-item><el-form-item v-for="field in [{key:'routePath',label:'技术路由'},{key:'componentKey',label:'组件标识'},{key:'menuCode',label:'菜单代码'},{key:'moduleCode',label:'模块代码'},{key:'permissionCode',label:'权限码'}]" :key="field.key" :label="`${field.label}（只读）`"><el-input :model-value="String(selected?.[field.key as keyof Menu]??'—')" readonly/></el-form-item></div><div class="actions" style="justify-content:flex-end"><el-button @click="dialog=false">取消</el-button><el-button type="primary" native-type="submit" :loading="saving">保存</el-button></div></el-form></el-dialog></template>
