<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, save, query } from '../../api/client'
import type { FormInstance } from 'element-plus'
import type { Shop, SkuConfig } from '../../api/types'
import RequestError from '../../components/RequestError.vue'

const shops=ref<Shop[]>([]),configs=ref<SkuConfig[]>([]),loading=ref(false),saving=ref(false),error=ref<Error|null>(null),dialog=ref(false),form=ref<FormInstance>(),selected=ref<SkuConfig>()
const values=reactive({shopId:'',displayName:'',sellerSku:'',sortOrder:0,enabled:true})
async function load(){loading.value=true;error.value=null;try{shops.value=await api<Shop[]>('/system/shops?marketCode=MY');if(!values.shopId&&shops.value.length)values.shopId=shops.value[0].id;if(values.shopId)configs.value=await api<SkuConfig[]>(`/admin/sku-config?${query({shopId:values.shopId})}`)}catch(e){error.value=e as Error}finally{loading.value=false}}
async function changeShop(){configs.value=await api<SkuConfig[]>(`/admin/sku-config?${query({shopId:values.shopId})}`)}
function edit(row?:SkuConfig){selected.value=row;Object.assign(values,{displayName:row?.displayName??'',sellerSku:row?.sellerSku??'',sortOrder:row?.sortOrder??0,enabled:row?.enabled??true});dialog.value=true}
async function submit(){if(!await form.value?.validate().catch(()=>false))return;saving.value=true;try{const body={...values};await save(selected.value?`/admin/sku-config/${selected.value.id}`:'/admin/sku-config',body,selected.value?'PUT':'POST');dialog.value=false;ElMessage.success('SKU 配置已保存');await load()}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
async function remove(row:SkuConfig){try{await ElMessageBox.confirm(`删除 ${row.sellerSku} 的映射？`,'删除 SKU 配置',{type:'warning',confirmButtonText:'删除',cancelButtonText:'取消'});await api(`/admin/sku-config/${row.id}`,{method:'DELETE'});ElMessage.success('SKU 配置已删除');await load()}catch(e){if(e instanceof Error)ElMessage.error(e.message)}}
onMounted(load)
</script>
<template><div class="page-head"><div><h1>SKU 配置</h1><p>按 Seller SKU 映射看板展示名称，未配置的 SKU 不会自动归类</p></div><el-button type="primary" :disabled="!values.shopId" @click="edit()">新增映射</el-button></div><RequestError :error="error" @retry="load"/><section class="surface table-panel"><div class="panel-head"><h2>SKU 映射</h2><el-select v-model="values.shopId" style="width:240px" @change="changeShop"><el-option v-for="shop in shops" :key="shop.id" :value="shop.id" :label="shop.shopName"/></el-select></div><el-table v-loading="loading" :data="configs" empty-text="暂无 SKU 映射"><el-table-column prop="displayName" label="看板展示名称" min-width="220"/><el-table-column prop="sellerSku" label="Seller SKU" min-width="220"/><el-table-column prop="sortOrder" label="排序" width="90" align="right"/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag size="small" :type="row.enabled?'success':'info'">{{ row.enabled?'启用':'停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="140" fixed="right"><template #default="{row}"><el-button text type="primary" size="small" @click="edit(row)">编辑</el-button><el-button text type="danger" size="small" @click="remove(row)">删除</el-button></template></el-table-column></el-table></section><el-dialog v-model="dialog" :title="selected?'编辑 SKU 映射':'新增 SKU 映射'" width="520px" destroy-on-close><el-form ref="form" :model="values" label-position="top" @submit.prevent="submit"><el-form-item label="Seller SKU" prop="sellerSku" :rules="[{required:true,message:'请输入 Seller SKU',trigger:'blur'}]"><el-input v-model="values.sellerSku" maxlength="100"/></el-form-item><el-form-item label="看板展示名称" prop="displayName" :rules="[{required:true,message:'请输入展示名称',trigger:'blur'}]"><el-input v-model="values.displayName" maxlength="100"/></el-form-item><el-form-item label="排序"><el-input-number v-model="values.sortOrder" :min="0" :max="2147483647" :precision="0"/></el-form-item><el-form-item label="状态"><el-switch v-model="values.enabled" active-text="启用" inactive-text="停用"/></el-form-item><div class="actions" style="justify-content:flex-end"><el-button @click="dialog=false">取消</el-button><el-button type="primary" native-type="submit" :loading="saving">保存</el-button></div></el-form></el-dialog></template>
