<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Plus } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import type { FormInstance, FormRules } from 'element-plus'
import { api, query, save } from '../../api/client'
import type { User, Role, Org, Page, Market } from '../../api/types'
import StatusBadge from '../../components/StatusBadge.vue'
import RequestError from '../../components/RequestError.vue'
const users=ref<User[]>([]),roles=ref<Role[]>([]),orgs=ref<Org[]>([]),markets=ref<Market[]>([]),page=ref(1),total=ref(0),loading=ref(false),saving=ref(false),error=ref<Error|null>(null),formError=ref(''),dialog=ref(false),form=ref<FormInstance>(),password=ref(''),passwordDialog=ref(false)
const filters=reactive({keyword:'',status:'',roleId:''}),editing=ref<string|null>(null),values=reactive({username:'',displayName:'',orgUnitId:'',marketCode:'',roleIds:[] as string[],status:'ACTIVE'})
const rules:FormRules={username:[{required:true,message:'请输入账号',trigger:'blur'},{max:64,message:'账号不能超过 64 字符',trigger:'blur'}],displayName:[{required:true,message:'请输入姓名',trigger:'blur'},{max:100,message:'姓名不能超过 100 字符',trigger:'blur'}],roleIds:[{type:'array',required:true,min:1,message:'请至少选择一个角色',trigger:'change'}]}
async function load(){loading.value=true;error.value=null;try{const result=await api<Page<User>>(`/admin/users?${query({...filters,page:page.value,pageSize:20})}`);users.value=result.items;total.value=result.total}catch(e){error.value=e as Error}finally{loading.value=false}}
async function edit(user?:User){editing.value=user?.id??null;Object.assign(values,{username:user?.username??'',displayName:user?.displayName??'',orgUnitId:user?.orgUnitId??'',marketCode:user?.marketCode??'',roleIds:user?.roles.map(r=>r.id)??[],status:user?.status??'ACTIVE'});formError.value='';dialog.value=true;try{[roles.value,orgs.value,markets.value]=await Promise.all([api<Role[]>('/admin/roles'),api<Org[]>('/admin/org-units'),api<Market[]>('/system/markets')])}catch(e){formError.value=(e as Error).message}}
async function submit(){if(!await form.value?.validate().catch(()=>false))return;saving.value=true;formError.value='';try{const result=await save<{temporaryPassword?:string}>(editing.value?`/admin/users/${editing.value}`:'/admin/users',values,editing.value?'PUT':'POST');dialog.value=false;ElMessage.success(editing.value?'用户已更新':'用户已创建');if(result?.temporaryPassword){password.value=result.temporaryPassword;passwordDialog.value=true}await load()}catch(e){formError.value=(e as Error).message}finally{saving.value=false}}
async function changeStatus(user:User){const status=user.status==='ACTIVE'?'DISABLED':'ACTIVE';try{await ElMessageBox.confirm(`确认${status==='ACTIVE'?'启用/解锁':'停用'} ${user.displayName}？`,'更新账号状态',{confirmButtonText:'确认',cancelButtonText:'取消',type:'warning'});await save(`/admin/users/${user.id}`,{status},'PUT');ElMessage.success('账号状态已更新');await load()}catch(e){if(e instanceof Error)ElMessage.error(e.message)}}
async function reset(user:User){try{await ElMessageBox.confirm(`为 ${user.displayName} 重置初始密码为 admin100？下次登录必须修改密码。`,'重置密码',{confirmButtonText:'重置密码',cancelButtonText:'取消',type:'warning'});const result=await save<{temporaryPassword:string}>(`/admin/users/${user.id}/reset-password`,{});password.value=result.temporaryPassword;passwordDialog.value=true}catch(e){if(e instanceof Error)ElMessage.error(e.message)}}
onMounted(()=>{void load()})
</script>
<template><div class="page-head"><div><h1>用户管理</h1><p>管理成员账号、角色与组织归属</p></div><el-button type="primary" @click="edit()"><el-icon><Plus/></el-icon>&nbsp;创建用户</el-button></div><form class="surface filter-bar" @submit.prevent="page=1;load()"><label class="filter-field">账号 / 姓名<el-input v-model="filters.keyword" placeholder="搜索账号或姓名" clearable/></label><label class="filter-field">账号状态<el-select v-model="filters.status" placeholder="全部状态" clearable><el-option label="正常" value="ACTIVE"/><el-option label="停用" value="DISABLED"/><el-option label="已锁定" value="LOCKED"/></el-select></label><el-button type="primary" native-type="submit">查询</el-button><el-button @click="filters.keyword='';filters.status='';page=1;load()">重置</el-button></form><RequestError :error="error" @retry="load"/><div class="surface table-panel"><el-table v-loading="loading" :data="users" empty-text="暂无匹配用户"><el-table-column prop="username" label="账号" min-width="150" show-overflow-tooltip/><el-table-column prop="displayName" label="姓名" min-width="130"/><el-table-column label="角色" min-width="200"><template #default="{row}"><div class="actions"><el-tag v-for="role in row.roles" :key="role.id" type="info" size="small">{{ role.roleName }}</el-tag></div></template></el-table-column><el-table-column label="负责市场" width="110"><template #default="{row}">{{ row.marketCode||'—' }}</template></el-table-column><el-table-column label="组织" min-width="130"><template #default="{row}">{{ row.orgUnitName??row.orgUnitId??'—' }}</template></el-table-column><el-table-column label="状态" width="95"><template #default="{row}"><StatusBadge :status="row.status"/></template></el-table-column><el-table-column prop="lastLoginAt" label="最近登录" min-width="180"/><el-table-column label="操作" width="220" fixed="right"><template #default="{row}"><el-button text type="primary" size="small" @click="edit(row)">编辑</el-button><el-button text type="primary" size="small" @click="reset(row)">重置密码</el-button><el-button text :type="row.status==='ACTIVE'?'danger':'primary'" size="small" @click="changeStatus(row)">{{ row.status==='ACTIVE'?'停用':row.status==='LOCKED'?'解锁':'启用' }}</el-button></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="page" :page-size="20" :total="total" layout="total, prev, pager, next" @current-change="load"/></div></div>
<el-dialog v-model="dialog" :title="editing?'编辑用户':'创建用户'" width="560px" destroy-on-close :close-on-click-modal="false"><el-alert v-if="formError" :title="formError" type="error" :closable="false"/><el-form ref="form" :model="values" :rules="rules" label-position="top" @submit.prevent="submit"><div class="form-grid"><el-form-item label="账号" prop="username"><el-input v-model="values.username" :readonly="!!editing" maxlength="64" autocomplete="off"/></el-form-item><el-form-item label="姓名" prop="displayName"><el-input v-model="values.displayName" maxlength="100"/></el-form-item><el-form-item class="full" label="角色" prop="roleIds"><el-select v-model="values.roleIds" multiple placeholder="请选择角色"><el-option v-for="r in roles" :key="r.id" :value="r.id" :label="r.roleName" :disabled="!r.enabled"/></el-select></el-form-item><el-form-item label="负责市场"><el-select v-model="values.marketCode" clearable placeholder="剪辑/市场负责人必填"><el-option v-for="market in markets" :key="market.marketCode" :value="market.marketCode" :label="market.marketName"/></el-select></el-form-item><el-form-item class="full" label="组织归属" prop="orgUnitId"><el-tree-select v-model="values.orgUnitId" :data="orgs" :props="{label:'name',value:'id',children:'children'}" node-key="id" check-strictly clearable placeholder="选择部门或小组" style="width:100%"/></el-form-item></div><el-alert v-if="!editing" title="所有新建用户初始密码统一为 admin100，首次登录时必须修改。" type="info" :closable="false"/><div class="actions" style="justify-content:flex-end"><el-button @click="dialog=false">取消</el-button><el-button type="primary" native-type="submit" :loading="saving">保存</el-button></div></el-form></el-dialog>
<el-dialog v-model="passwordDialog" title="初始密码" width="420px" :close-on-click-modal="false" @closed="password='' "><p class="muted" style="margin-bottom:16px">初始密码统一为 admin100，请交给对应用户并提醒首次登录修改。</p><el-input :model-value="password" readonly aria-label="初始密码"/><template #footer><el-button type="primary" @click="passwordDialog=false">已记录</el-button></template></el-dialog></template>
