<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Coin, Goods, InfoFilled, Refresh, ShoppingBag, Tickets, View } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { api, query, download } from '../../api/client'
import type { Overview, Trend, Funnel, Ads, OrderStatus, AfterSales, Metric, Market } from '../../api/types'
import { comparisonLabel, dateRangeError, presetRange, number } from '../../api/format.mjs'
import { useAuth } from '../../stores/auth'
import Chart from '../../components/Chart.vue'
import MetricChange from '../../components/MetricChange.vue'
import RequestError from '../../components/RequestError.vue'
import { spark, combo } from './charts'
const auth=useAuth(),busy=ref(false),exporting=ref(false),error=ref<Error|null>(null),markets=ref<Market[]>([]),marketCode=ref('MY')
const initialRange=presetRange('yesterday') as [string,string],dates=ref<[string,string]>(initialRange),period=ref('yesterday')
const overview=ref<Overview>(),sales=ref<Trend[]>([]),funnel=ref<Funnel>(),ads=ref<Ads>(),statuses=ref<OrderStatus[]>([]),after=ref<AfterSales>(),loaded=ref(false)
const applied=ref({marketCode:'MY',dateFrom:initialRange[0],dateTo:initialRange[1],comparisonPeriod:'yesterday'})
const single=computed(()=>applied.value.dateFrom===applied.value.dateTo),compare=computed(()=>overview.value?.comparisonLabel??comparisonLabel(applied.value.comparisonPeriod))
const currency=computed(()=>overview.value?.currencyCode??markets.value.find(m=>m.marketCode===marketCode.value)?.currencyCode??'MYR')
const currencyDisplay=computed(()=>currency.value==='MYR'?'RM':currency.value)
const metricIcons:Record<string,unknown>={gmv:ShoppingBag,orderCount:Tickets,soldQty:Goods,skuOrderCount:Goods,aov:Coin,refundAmount:Refresh}
const kpis=computed(()=>[{key:'gmv',label:'GMV',hint:'Shop Analytics 每日 GMV',money:true},{key:'orderCount',label:'订单数',hint:'Shop Analytics 每日订单数'},{key:'soldQty',label:'商品成交件数',hint:'Shop Analytics 每日商品成交件数'},{key:'skuOrderCount',label:'SKU 订单数',hint:'Shop Analytics 每日 SKU 订单数；不是成交件数'},{key:'aov',label:'平均订单金额',hint:'AOV = 总 GMV ÷ 总订单数',money:true},{key:'refundAmount',label:'退款金额',hint:'Shop Analytics 每日退款金额',money:true,direction:'lower'}])
const getMetric=(key:string)=>overview.value?.[key as keyof Overview] as Metric|undefined
const pct=(v:number|null|undefined)=>v==null?'—':`${number(v*100,1)}%`
const productNotice=computed(()=>{if(!loaded.value||!funnel.value)return '';if(funnel.value.source==='SHOP_ANALYTICS_PARTIAL')return '当前范围没有可精确匹配的商品报表，商品漏斗暂用 Shop Analytics 的曝光、点击和 SKU 订单数据；加购相关字段需要导入与当前日期范围一致的商品报表。顶部 GMV、订单、成交件数、SKU 订单和退款金额不受影响。';if(funnel.value.source==='NONE')return '当前范围没有 Shop Analytics 或可精确匹配的商品报表，商品漏斗无法计算。';return ''})
const funnelSourceLabel=computed(()=>({PRODUCT_PERIOD:'商品区间报表',PRODUCT_DAILY:'商品单日数据',SHOP_ANALYTICS_PARTIAL:'Shop Analytics（部分字段）',NONE:'无可用数据'}[funnel.value?.source??'NONE']))
const funnelStatus=computed(()=>({PRODUCT_PERIOD:'完整商品数据',PRODUCT_DAILY:'完整商品数据',SHOP_ANALYTICS_PARTIAL:'部分数据',NONE:'无可用数据'}[funnel.value?.source??'NONE']))
const funnelStatusType=computed(()=>funnel.value?.source==='NONE'?'warning':funnel.value?.source==='SHOP_ANALYTICS_PARTIAL'?'info':'success')
const stages=computed(()=>[{label:'商品曝光次数',value:funnel.value?.impressions,rateLabel:'',rate:null,aux:'去重曝光',extra:funnel.value?.uniqueImpressions},{label:'商品点击量',value:funnel.value?.clicks,rateLabel:'CTR',rate:funnel.value?.ctr,aux:'去重点击',extra:funnel.value?.uniqueClicks},{label:'加购次数',value:funnel.value?.addToCartCount,rateLabel:'加购率',rate:funnel.value?.addToCartRate,aux:'加购用户',extra:funnel.value?.addedUserCount},{label:'SKU 订单数',value:funnel.value?.skuOrderCount,rateLabel:'CTOR',rate:funnel.value?.ctor,aux:'下单客户',extra:funnel.value?.estimatedCustomerCount}])
const adMetrics=computed(()=>[{label:'广告花费',metric:ads.value?.spend,direction:'neutral',money:true},{label:'广告归因收入',metric:ads.value?.attributedRevenue,direction:'higher',money:true},{label:'ROI',metric:ads.value?.roi,direction:'higher'},{label:'CPO',metric:ads.value?.cpo,direction:'lower',money:true}])
const currentAfterMetrics=computed(()=>[{label:'退款金额',metric:after.value?.refundAmount,money:true},{label:'取消订单数',metric:after.value?.cancelOrderCount}])
const cumulativeAfterMetrics=computed(()=>[{label:'已退款商品件数',metric:after.value?.refundedQty},{label:'退款客户数',metric:after.value?.refundCustomerCount}])
const afterSource=computed(()=>after.value?.productDataRange?`商品售后累计数据：${after.value.productDataRange.dateFrom} 至今`:'商品售后累计数据暂无可用报表')
const afterUpdatedAt=computed(()=>after.value?.productDataRange?.dateTo)
const statusNames:Record<string,string>={UNPAID:'未付款',PAID:'已付款',SHIPPED:'已发货',COMPLETED:'已完成',CANCELLED:'已取消',REFUNDED:'已退款',UNKNOWN:'未知状态'}
const statusTotal=computed(()=>statuses.value.reduce((sum,s)=>sum+s.count,0))
const statusOption=computed(()=>({tooltip:{trigger:'item',confine:true},series:[{type:'pie',radius:['64%','86%'],center:['50%','50%'],label:{show:false},itemStyle:{borderWidth:2,borderColor:'#fff'},data:statuses.value.map(s=>({name:statusNames[s.status]??s.status,value:s.count}))}]}))
let request=0
async function load(){const validation=dateRangeError(dates.value?.[0],dates.value?.[1]);if(validation){ElMessage.warning(validation);return}const current=++request;busy.value=true;error.value=null;loaded.value=false;overview.value=undefined;sales.value=[];funnel.value=undefined;ads.value=undefined;statuses.value=[];after.value=undefined;const filters={marketCode:marketCode.value,dateFrom:dates.value[0],dateTo:dates.value[1],comparisonPeriod:period.value},suffix=`?${query(filters)}`;try{const values=await Promise.all([api<Overview>('/dashboard/overview'+suffix),api<Trend[]>('/dashboard/sales-trend'+suffix),api<Funnel>('/dashboard/product-funnel'+suffix),api<Ads>('/dashboard/ads'+suffix),api<OrderStatus[]>('/dashboard/order-status'+suffix),api<AfterSales>('/dashboard/after-sales'+suffix)]);if(current!==request)return;[overview.value,sales.value,funnel.value,ads.value,statuses.value,after.value]=values;applied.value=filters;loaded.value=true}catch(e){if(current===request)error.value=e as Error}finally{if(current===request)busy.value=false}}
function choosePeriod(value:string){period.value=value;if(value==='custom')return;dates.value=presetRange(value) as [string,string];void load()}
async function exportData(type:string){exporting.value=true;try{await download(`/exports/${type}`,applied.value);ElMessage.success('导出文件已下载')}catch(e){ElMessage.error((e as Error).message)}finally{exporting.value=false}}
onMounted(async()=>{void load();try{markets.value=await api<Market[]>('/system/markets')}catch{/* MY is the documented initial market; no invented additional markets. */}})
</script>
<template>
  <div class="dashboard-shell">
  <h1 class="sr-only">经营驾驶舱</h1>
  <div class="surface dashboard-filters">
    <div class="actions"><label class="inline-filter"><span>业务日期</span><el-radio-group v-model="period" size="small" aria-label="业务日期快捷选择" @change="choosePeriod"><el-radio-button value="today">今日</el-radio-button><el-radio-button value="yesterday">昨日</el-radio-button><el-radio-button value="week">本周</el-radio-button><el-radio-button value="month">本月</el-radio-button><el-radio-button value="custom">自定义</el-radio-button></el-radio-group><el-date-picker v-if="period==='custom'" v-model="dates" type="daterange" value-format="YYYY-MM-DD" format="YYYY/MM/DD" start-placeholder="开始日期" end-placeholder="结束日期" :clearable="false"/></label><label class="inline-filter"><span>市场</span><el-select v-model="marketCode" aria-label="市场" style="width:170px"><el-option v-for="m in markets.length?markets:[{marketCode:'MY',marketName:'马来西亚',currencyCode:'MYR'}]" :key="m.marketCode" :value="m.marketCode" :label="`${m.marketName} (${m.marketCode})`"/></el-select></label><el-button type="primary" :loading="busy" @click="load">查询</el-button></div>
    <el-button text aria-label="刷新数据" :disabled="busy" @click="load"><el-icon><Refresh/></el-icon></el-button>
  </div>
  <RequestError :error="error" @retry="load"/>
  <el-alert v-if="productNotice" class="data-alert" :type="funnel?.source==='NONE'?'warning':'info'" :closable="false" :title="productNotice"/>
  <div v-if="busy" class="surface panel" aria-label="正在加载经营数据" aria-busy="true"><el-skeleton :rows="12" animated/></div>
  <template v-else>
  <section class="kpi-grid" aria-label="核心经营指标"><article v-for="k in kpis" :key="k.key" class="surface kpi"><div class="kpi-top"><span class="metric-icon"><el-icon :size="25"><component :is="metricIcons[k.key]"/></el-icon></span><div class="kpi-label"><span>{{ k.label }}</span><el-tooltip :content="k.hint" placement="top"><button class="info-button" :aria-label="k.hint"><el-icon><InfoFilled/></el-icon></button></el-tooltip></div></div><div class="kpi-value number"><small v-if="k.money">{{ currencyDisplay }}</small>{{ number(getMetric(k.key)?.value,k.money?2:0) }}</div><MetricChange :value="getMetric(k.key)?.comparePrevious" :status="getMetric(k.key)?.comparePreviousStatus" :direction="k.direction" :label="compare"/><MetricChange v-if="single" :value="getMetric(k.key)?.compare7dAvg" :status="getMetric(k.key)?.compare7dAvgStatus" :direction="k.direction" label="较前 7 日均值"/><Chart v-if="getMetric(k.key)?.trend?.length" :option="spark(getMetric(k.key),k.key==='refundAmount'?'#c34b4b':k.key==='aov'?'#6f887d':k.key==='skuOrderCount'?'#496f60':k.key==='soldQty'?'#7fa18f':'#2f5d4b')" :height="43" :label="`${k.label}小趋势`"/><div v-else class="no-spark">{{ loaded?'暂无趋势数据':'等待数据加载' }}</div></article></section>
  <section class="analysis-grid">
    <article class="surface panel sales-panel"><div class="panel-head"><h2>销售趋势</h2><small class="legend-label blue">■ GMV ({{ currencyDisplay }})</small><small class="legend-label purple">● 订单数</small></div><Chart v-if="sales.length" :option="combo(sales,'gmv','orderCount',`GMV (${currencyDisplay})`,'订单数')" :height="255" label="GMV 柱状图与订单数折线图"/><el-empty v-else description="此范围暂无销售趋势" :image-size="64"/></article>
    <article class="surface panel funnel-panel"><div class="panel-head"><h2>商品转化漏斗 <small class="muted">从曝光到下单的转化表现</small></h2></div><div class="funnel-rows"><div v-for="(s,i) in stages" :key="s.label" class="funnel-row"><div class="funnel-shape" :style="{'--stage':i}"></div><div class="funnel-count"><small>{{ s.label }}</small><strong class="number">{{ number(s.value) }}</strong></div><div v-if="s.rateLabel" class="funnel-rate"><small class="muted">{{ s.rateLabel }}</small><span class="number">{{ pct(s.rate) }}</span></div><div v-else></div><div class="funnel-extra"><small class="muted">{{ s.aux }}</small><span class="number">{{ number(s.extra) }}</span></div></div></div></article>
    <article class="surface panel ads-panel"><div class="panel-head"><h2>GMV Max 广告效果 <small class="muted">仅包含已归因的广告数据</small></h2><small>币种: {{ ads?.currencyCode ?? 'USD' }}</small></div><div class="ad-metrics"><div v-for="m in adMetrics" :key="m.label"><small class="muted">{{ m.label }}</small><strong class="number">{{ number(m.metric?.value,2) }}</strong><MetricChange :value="m.metric?.comparePrevious" :status="m.metric?.comparePreviousStatus" :direction="m.direction"/></div></div><Chart v-if="ads?.trend?.length" :option="combo(ads.trend,'spend','attributedRevenue',`Cost (${ads.currencyCode==='MYR'?'RM':ads.currencyCode})`,`Gross Revenue (${ads.currencyCode==='MYR'?'RM':ads.currencyCode})`)" :height="146" label="广告花费与广告归因收入趋势"/><div v-else class="empty-inline">此范围暂无广告趋势</div></article>
  </section>
  <section class="bottom-grid">
    <article class="surface panel"><div class="panel-head"><h2>订单状态分布</h2></div><div v-if="statusTotal" class="status-layout"><div class="donut"><Chart :option="statusOption" :height="166" label="订单状态数量分布环形图"/><div class="donut-center"><strong class="number">{{ number(statusTotal) }}</strong><small class="muted">总订单数</small></div></div><div class="status-list"><div v-for="(s,i) in statuses" :key="s.status"><span class="status-dot" :class="`dot-${i%6}`"/><span>{{ statusNames[s.status]??s.status }}</span><small class="number muted">{{ pct(s.ratio) }}</small><b class="number">({{ number(s.count) }})</b></div></div></div><el-empty v-else description="暂无订单状态数据" :image-size="52"/></article>
    <article class="surface panel after-panel"><div class="panel-head"><h2>售后情况 <small class="muted">基于订单数据统计</small></h2></div><div class="after-grid"><div v-for="m in [...currentAfterMetrics,...cumulativeAfterMetrics]" :key="m.label"><span class="after-icon">×</span><div><small class="muted">{{ m.label }}</small><strong class="number"><small v-if="'money' in m && m.money">{{ currencyDisplay }} </small>{{ number(m.metric?.value,('money' in m && m.money)?2:0) }}</strong><MetricChange v-if="m.metric" :value="m.metric.comparePrevious" :status="m.metric.comparePreviousStatus" direction="lower" :label="compare"/></div></div></div></article>
    <article class="surface panel"><div class="panel-head"><h2>商品访客与转化</h2></div><div class="store-grid"><div v-for="(m,i) in [{label:'商品访客数',metric:overview?.visitorCount},{label:'店铺转化率',metric:overview?.conversionRate}]" :key="m.label"><span class="store-icon"><el-icon><View v-if="!i"/><Goods v-else/></el-icon></span><div><small class="muted">{{ m.label }}</small><strong class="number">{{ i?pct(m.metric?.value):number(m.metric?.value) }}</strong><MetricChange :value="m.metric?.comparePrevious" :status="m.metric?.comparePreviousStatus" :label="compare"/></div><Chart v-if="m.metric?.trend?.length" :option="spark(m.metric,i?'#6f887d':'#2f5d4b')" :height="58" :label="m.label+'趋势'"/><div v-else class="no-spark">暂无趋势数据</div></div></div></article>
  </section>
  </template></div>
</template>
<style scoped>
.dashboard-shell{max-width:none;margin:0;padding:0 0 16px}.dashboard-filters{display:flex;justify-content:space-between;align-items:center;padding:12px 16px;margin-bottom:12px}.inline-filter{display:flex;align-items:center;gap:10px;font-size:12px;color:var(--text-secondary)}.inline-filter .el-date-editor{width:260px}.data-alert{margin-bottom:12px}
.kpi-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px;margin-bottom:12px}.kpi{height:214px;padding:16px 16px 9px;overflow:hidden}.kpi-top{display:flex;align-items:center;gap:10px}.metric-icon{display:grid;place-items:center;width:36px;height:36px;border-radius:8px;color:#344B40;background:#F2F4F3;border:1px solid #E5E9E6}.kpi-label{display:flex;align-items:center;justify-content:space-between;gap:5px;font-size:13px;font-weight:600;color:#171A18}.info-button{padding:0;border:0;background:transparent;color:#929893;display:grid;place-items:center;width:16px;height:16px}.info-button:hover{color:#171A18}.kpi-value{font-size:28px;letter-spacing:-.55px;font-weight:650;color:#171A18;white-space:nowrap;margin:13px 0 6px;display:flex;gap:5px;align-items:baseline}.kpi-value small{font-size:14px;font-weight:600;letter-spacing:0}.no-spark{height:43px;display:flex;align-items:center;color:var(--text-secondary);font-size:10px}
.analysis-grid{display:grid;grid-template-columns:1.23fr .76fr .98fr;gap:12px;margin-bottom:12px}.panel{padding:16px;min-width:0}.panel-head{position:relative;display:flex;align-items:center;justify-content:space-between;gap:9px;margin-bottom:14px;min-height:24px}.panel-head h2{font-size:15px;line-height:1.35;font-weight:650;color:#171A18;white-space:nowrap}.panel-head h2::before{content:'';display:inline-block;width:2px;height:15px;margin:0 8px 0 0;background:#344B40;vertical-align:-2px}.panel-head h2 small{font-weight:400;font-size:11px;margin-left:6px;color:#707872}.panel-head>small{font-size:11px;color:#707872}.legend-label{font-size:11px}.blue{color:#344B40}.purple{color:#AEB6B1}
.funnel-rows{display:grid;gap:5px}.funnel-row{display:grid;grid-template-columns:74px 1.22fr .72fr .86fr;align-items:center;gap:7px;background:#fff;border:1px solid #E5E9E6;border-radius:6px;padding:5px 7px;height:57px}.funnel-row small{font-size:10.5px;display:block;white-space:nowrap;color:#626A65}.funnel-row strong{font-size:18px;line-height:1;display:block;margin-top:4px;color:#171A18}.funnel-row span.number{font-size:14px;display:block;margin-top:5px;color:#171A18}.funnel-shape{width:calc(72px - var(--stage)*9px);height:49px;justify-self:center;background:#344B40;opacity:calc(1 - var(--stage)*.1);clip-path:polygon(0 0,100% 0,85% 100%,15% 100%)}.funnel-row:nth-child(2) .funnel-shape{background:#64756C}.funnel-row:nth-child(3) .funnel-shape{background:#8E9992}.funnel-row:nth-child(4) .funnel-shape{background:#B5BCB7}.funnel-rate,.funnel-extra{border-left:1px solid #EDF0EE;padding-left:7px}
.ad-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));margin:3px 0 8px}.ad-metrics>div{padding:0 12px;border-right:1px solid #E5E9E6}.ad-metrics>div:first-child{padding-left:0}.ad-metrics>div:last-child{border:0}.ad-metrics small{font-size:10.5px;white-space:nowrap}.ad-metrics strong{display:block;color:#171A18;font-size:20px;font-weight:650;line-height:1;margin:9px 0 4px}
.bottom-grid{display:grid;grid-template-columns:.92fr .88fr 1.8fr;gap:12px}.status-layout{display:grid;grid-template-columns:52% 48%;align-items:center}.donut{position:relative}.donut-center{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;pointer-events:none}.donut-center strong{font-size:24px;font-weight:650;color:#171A18}.donut-center small{font-size:10px;margin-top:3px}.status-list{display:grid;gap:10px}.status-list>div{display:grid;grid-template-columns:8px 1fr auto auto;align-items:center;gap:7px;font-size:11.5px;color:#171A18}.status-list b{font-weight:400}.status-list small{font-size:10.5px}.status-dot{width:7px;height:7px;border-radius:50%;background:#344B40}.dot-1{background:#64756C}.dot-2{background:#8E9992}.dot-3{background:#AEB6B1}.dot-4{background:#C4CAC6}.dot-5{background:#D9DEDA}
.after-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px 14px}.after-grid>div{display:flex;gap:10px;border-bottom:1px solid #EDF0EE;padding:8px 1px 9px}.after-grid>div:nth-last-child(-n+2){border-bottom:0}.after-icon{margin-top:1px;flex:0 0 32px;height:32px;display:grid;place-items:center;border-radius:6px;background:#FBEFEF;color:#C34848;font-size:22px;line-height:1}.after-grid small,.store-grid small{font-size:10.5px}.after-grid strong{display:block;color:#171A18;font-size:17px;font-weight:650;line-height:1;margin:5px 0 2px}.after-grid strong small{font-size:10px;font-weight:600}
.store-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.store-grid>div{min-width:0;position:relative;display:grid;grid-template-columns:46px 1fr;grid-template-rows:auto 60px;background:#F7F8F7;border:1px solid #E5E9E6;padding:11px;border-radius:7px;overflow:hidden}.store-grid>div :deep([role="img"]){grid-column:1/-1}.store-icon{display:grid;place-items:center;width:36px;height:36px;color:#344B40;background:#F2F4F3;border:1px solid #E5E9E6;border-radius:7px;font-size:21px}.store-grid strong{color:#171A18;font-size:24px;font-weight:650;line-height:1;display:block;margin:7px 0 3px}
@media(max-width:1300px){.kpi-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.analysis-grid{grid-template-columns:1.1fr 1fr}.sales-panel{grid-column:1/-1}.bottom-grid{grid-template-columns:1fr 1fr}.bottom-grid>article:last-child{grid-column:1/-1}}
@media(max-width:767px){.dashboard-shell{padding:0 0 12px}.dashboard-filters{padding:12px;align-items:flex-start}.dashboard-filters>.actions{width:100%}.inline-filter{width:100%;display:grid;gap:6px}.inline-filter .el-date-editor{width:100%}.kpi-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.kpi{height:194px;padding:12px}.metric-icon{width:34px;height:34px}.kpi-value{font-size:22px}.analysis-grid,.bottom-grid{grid-template-columns:1fr;gap:10px}.sales-panel,.bottom-grid>article:last-child{grid-column:auto}.panel-head h2{font-size:15px;white-space:normal}.funnel-row{grid-template-columns:58px 1fr .7fr .8fr}.funnel-shape{width:calc(56px - var(--stage)*7px)}.ad-metrics>div{padding:0 6px}.ad-metrics strong{font-size:16px}.status-layout{grid-template-columns:1fr 1fr}.after-grid{grid-template-columns:1fr}.after-grid>div:nth-last-child(2){border-bottom:1px solid #EDF0EE}.store-grid{gap:8px}.store-grid>div{padding:8px;grid-template-columns:40px 1fr}}
</style>
