<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import type { FormInstance, FormRules } from 'element-plus'
import { DataBoard, Connection, User } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { save } from '../api/client'
import { passwordError } from '../api/format.mjs'
import { useAuth } from '../stores/auth'
import { clearSession } from '../router'
import logo from '../assets/brand/herbmoda-logo-dark.png'
const route = useRoute(), router = useRouter(), auth = useAuth(), form = ref<FormInstance>(), busy = ref(false), error = ref('')
const forced = computed(() => route.path === '/force-change-password')
const values = reactive({ username:'', password:'', oldPassword:'', newPassword:'', confirm:'' })
const rules: FormRules = { username:[{required:true,message:'请输入账号',trigger:'blur'}],password:[{required:true,message:'请输入密码',trigger:'blur'}],oldPassword:[{required:true,message:'请输入原密码',trigger:'blur'}],newPassword:[{validator:(_r,v,cb)=>{const message=passwordError(v);cb(message ? new Error(message) : undefined)},trigger:'blur'}],confirm:[{validator:(_r,v,cb)=>cb(v && v===values.newPassword ? undefined : new Error('两次输入的密码不一致')),trigger:'blur'}] }
async function submit() { if (!await form.value?.validate().catch(()=>false)) return; busy.value=true;error.value='';try { if(forced.value){await save('/auth/change-password',{oldPassword:values.oldPassword,newPassword:values.newPassword});clearSession();ElMessage.success('密码已更新，请重新登录');await router.replace('/login')}else{await save('/auth/login',{username:values.username,password:values.password});await auth.load();const redirect=String(route.query.redirect??'');const target=auth.allMenus.some(menu=>menu.routePath===redirect)?redirect:'/dashboard';await router.replace(target)} } catch(e){error.value=(e as Error).message}finally{busy.value=false;values.password=''} }
</script>
<template><main class="auth-page"><div class="auth-copy" aria-hidden="true"><div class="copy-brand"><img :src="logo" alt=""/><span><strong>HERBMODA</strong><small>COMMERCE INTELLIGENCE</small></span></div><small class="copy-kicker">DATA DRIVES<br/>A MORE RADIANT TOMORROW</small><div class="copy-message"><h2>Insight for<br/>a More Radiant World</h2><p>Unify data. Empower decisions.<br/>Grow a more beautiful tomorrow.</p></div><div class="copy-traits"><span><i><el-icon><DataBoard/></el-icon></i>DEEPER<br/>INSIGHTS</span><span><i><el-icon><Connection/></el-icon></i>SMARTER<br/>OPERATIONS</span><span><i><el-icon><User/></el-icon></i>BRIGHTER<br/>GROWTH</span></div></div><div class="auth-card surface"><div class="auth-brand"><img :src="logo" alt="HERBMODA"/><span><strong>HERBMODA</strong><small>Commerce Intelligence</small></span></div><h1>{{ forced ? '设置您的新密码' : '账号登录' }}</h1><p v-if="forced" class="muted">首次登录需要修改临时密码，完成后即可使用系统。</p><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" role="alert"/><el-form ref="form" :model="values" :rules="rules" label-position="top" @submit.prevent="submit"><template v-if="!forced"><el-form-item label="账号" prop="username"><el-input v-model="values.username" autocomplete="username" placeholder="请输入账号" size="large"/></el-form-item><el-form-item label="密码" prop="password"><el-input v-model="values.password" type="password" show-password autocomplete="current-password" placeholder="请输入密码" size="large"/></el-form-item></template><template v-else><el-form-item label="原密码" prop="oldPassword"><el-input v-model="values.oldPassword" type="password" show-password autocomplete="current-password"/></el-form-item><el-form-item label="新密码" prop="newPassword"><el-input v-model="values.newPassword" type="password" show-password autocomplete="new-password"/><small class="muted">至少 10 位，包含字母、数字、符号中的两类</small></el-form-item><el-form-item label="确认新密码" prop="confirm"><el-input v-model="values.confirm" type="password" show-password autocomplete="new-password"/></el-form-item></template><el-button class="submit" type="primary" native-type="submit" size="large" :loading="busy">{{ forced ? '保存并重新登录' : '登录' }}</el-button></el-form></div></main></template>
<style scoped>
.auth-page{min-height:100vh;display:grid;grid-template-columns:minmax(240px,.72fr) minmax(360px,1.25fr) minmax(380px,.78fr);align-items:center;gap:24px;padding:clamp(24px,3vw,56px);position:relative;isolation:isolate;overflow:hidden;background:radial-gradient(circle at 18% 18%,rgba(255,255,255,.95),transparent 34%),radial-gradient(circle at 74% 10%,rgba(181,207,233,.4),transparent 34%),linear-gradient(135deg,#F8FBFD 0%,#EAF1F7 46%,#F7FAFC 100%)}
.auth-page::before{content:'';position:absolute;z-index:-2;left:clamp(260px,23vw,340px);top:50%;transform:translateY(-50%);width:min(62vw,940px);height:min(82vh,800px);background:url('../assets/brand/radiant-oil-capsules-main.png') center/contain no-repeat;filter:saturate(.84) contrast(.98);mix-blend-mode:multiply;opacity:.98;pointer-events:none}
.auth-page::after{content:'';position:absolute;z-index:-3;left:clamp(70px,30vw,480px);bottom:-7vh;width:min(34vw,460px);height:min(52vh,560px);background:url('../assets/brand/glowing-tomato-mask.png') center bottom/contain no-repeat;filter:grayscale(.14) saturate(.7);opacity:.22;pointer-events:none}
.auth-card{grid-column:3;width:min(420px,100%);max-width:100%;padding:36px;background:rgba(255,255,255,.86);border:1px solid #E5EAF0;border-radius:18px;box-shadow:0 22px 60px rgba(26,39,55,.14);backdrop-filter:blur(22px) saturate(125%);justify-self:end;position:relative;z-index:1}
.auth-copy{grid-column:1;align-self:stretch;display:flex;flex-direction:column;justify-content:space-between;padding:2vh 0 7vh;position:relative;z-index:1;color:var(--hm-text)}.copy-brand{display:flex;align-items:center;gap:10px}.copy-brand img{width:34px;height:38px;object-fit:contain}.copy-brand strong{font-size:24px;letter-spacing:.16em;font-weight:650}.copy-brand small{display:block;margin-top:5px;color:var(--hm-text-secondary);font-size:9px;letter-spacing:.18em}.copy-kicker{font-size:10px;line-height:1.45;letter-spacing:.18em;color:#7A8796;margin-top:7vh}.copy-message h2{font-size:clamp(26px,2.2vw,42px);line-height:1.12;letter-spacing:-.035em;font-weight:650}.copy-message p{margin-top:16px;color:#667085;font-size:16px;line-height:1.45}.copy-traits{display:flex;gap:22px;color:#7A8796;font-size:9px;letter-spacing:.13em;line-height:1.35}.copy-traits span{display:grid;gap:8px}.copy-traits i{width:34px;height:34px;border:1px solid #D9E2EB;border-radius:50%;display:grid;place-items:center;color:#5F8FBE;font-size:20px;font-style:normal;line-height:1;background:rgba(255,255,255,.58)}
.auth-brand{display:flex;align-items:center;gap:10px;color:var(--hm-text);margin-bottom:32px}.auth-brand img{width:32px;height:34px;object-fit:contain}.auth-brand strong{display:block;font-size:16px;letter-spacing:.12em;font-weight:650}.auth-brand small{display:block;margin-top:2px;color:var(--hm-text-secondary);font-size:9px;letter-spacing:.04em}
.auth-card h1{font-size:22px;margin-bottom:24px;font-weight:650;color:var(--hm-text)}.auth-card p{font-size:13px;line-height:1.7;margin:-12px 0 20px}.submit{width:100%;height:48px;margin-top:12px;border-radius:10px}
.auth-card :deep(.el-input__wrapper){min-height:48px;border-radius:10px}.auth-card :deep(.el-form-item){margin-bottom:18px}.auth-card :deep(.el-alert){margin-bottom:20px}
@media(max-width:1100px){.auth-page{grid-template-columns:minmax(180px,.8fr) minmax(360px,1fr);padding:24px}.auth-copy{grid-column:1}.auth-card{grid-column:2;justify-self:center}.auth-page::before{left:-12vw;width:72vw;opacity:.8}.auth-page::after{left:16vw;width:42vw;opacity:.14}.copy-message h2{font-size:30px}.copy-message p{font-size:14px}}
@media(max-width:767px){.auth-page{display:flex;width:100%;max-width:100vw;justify-content:center;padding:20px}.auth-copy{display:none}.auth-page::before{left:-28vw;width:110vw;height:72vh;opacity:.13}.auth-page::after{left:auto;right:-30vw;bottom:-12vh;width:72vw;opacity:.06}.auth-card{width:calc(100vw - 40px);min-width:0;padding:28px 24px;box-shadow:0 18px 48px rgba(26,39,55,.12)}.auth-card :deep(.el-form),.auth-card :deep(.el-form-item),.auth-card :deep(.el-input){min-width:0}.auth-brand{margin-bottom:26px}}
</style>
