export function number(value, digits = 0) { return value == null || !Number.isFinite(Number(value)) ? '—' : new Intl.NumberFormat('zh-CN', { minimumFractionDigits: digits, maximumFractionDigits: digits }).format(Number(value)) }
export function changeTone(value, direction = 'higher') { if (value == null || value === 0 || direction === 'neutral') return 'neutral'; return (value > 0) === (direction === 'higher') ? 'positive' : 'negative' }
export function comparisonLabel(period) { return ({ today: '较昨日', yesterday: '较前日', week: '较上周同期', month: '较上月同期', custom: '较上一周期' })[period] ?? '较上一周期' }
export function dateRangeError(from, to) { if (!from || !to) return '请选择完整日期范围'; const start = Date.parse(from), end = Date.parse(to); if (!Number.isFinite(start) || !Number.isFinite(end)) return '日期格式无效'; const days = (end - start) / 86400000; return days < 0 ? '开始日期不能晚于结束日期' : days >= 366 ? '日期范围最多 366 天' : '' }
export function presetRange(preset,now=new Date()){const end=new Date(now.getFullYear(),now.getMonth(),now.getDate()),start=new Date(end);if(preset==='yesterday'){start.setDate(start.getDate()-1);end.setDate(end.getDate()-1)}else if(preset==='week')start.setDate(start.getDate()-((start.getDay()+6)%7));else if(preset==='month')start.setDate(1);const text=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return [text(start),text(end)]}
export function flattenMenus(menus) { return menus.flatMap(menu => [menu, ...flattenMenus(menu.children ?? [])]) }
export function navigationMenus(menus, supportedPaths, isAdmin) { return menus.filter(menu => menu.enabled && supportedPaths.includes(menu.routePath) && (!menu.routePath.startsWith('/admin/') || isAdmin)) }
export function validateFile(file) { if (!file || !/\.(xlsx|xls)$/i.test(file.name)) return '请选择 .xlsx 或 .xls 文件'; return file.size > 100 * 1024 * 1024 ? '文件不能超过 100 MB' : file.size === 0 ? '文件为空，请重新选择' : '' }
export function passwordError(value) { return value.length < 10 || [/[a-zA-Z]/, /[0-9]/, /[^a-zA-Z0-9]/].filter(re => re.test(value)).length < 2 ? '至少 10 位，包含字母、数字、符号中的两类' : '' }
