<script setup lang="ts">
import { onMounted, onBeforeUnmount, ref, reactive } from 'vue'
import { UploadFilled, Refresh } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import type { FormInstance, UploadFile } from 'element-plus'
import { api, query } from '../../api/client'
import type { Market, Shop, ImportTask, ImportError, Page } from '../../api/types'
import { validateFile } from '../../api/format.mjs'
import { useAuth } from '../../stores/auth'
import StatusBadge from '../../components/StatusBadge.vue'
import RequestError from '../../components/RequestError.vue'
const auth=useAuth(),form=ref<FormInstance>(),busy=ref(false),loading=ref(false),error=ref<Error|null>(null),contextError=ref<Error|null>(null),detailError=ref<Error|null>(null)
const markets=ref<Market[]>([]),shops=ref<Shop[]>([]),files=ref<UploadFile[]>([]),tasks=ref<ImportTask[]>([]),total=ref(0),page=ref(1),source=ref(''),status=ref(''),drawer=ref(false),selected=ref<ImportTask>(),errors=ref<ImportError[]>([]),errorPage=ref(1),errorTotal=ref(0),detailBusy=ref(false)
const values=reactive({sourceType:'SHOP_ANALYTICS',marketCode:'MY',shopId:'',bizDate:''})
const sources=[{value:'SHOP_ANALYTICS',label:'Shop Analytics · 店铺日数据'},{value:'PRODUCT_DAILY',label:'商品数据 · 历史区间/单日均支持'},{value:'ORDER_DETAIL',label:'订单明细'},{value:'AFFILIATE_ORDER',label:'达人订单 · 联盟订单'},{value:'GMV_MAX_CAMPAIGN',label:'GMV Max · 广告数据'}]
const states=['CREATED','VALIDATING','IMPORTING','AGGREGATING','SUCCESS','FAILED','AGGREGATE_FAILED']
let timer:ReturnType<typeof setTimeout>|undefined,alive=true
async function context(){contextError.value=null;try{markets.value=await api<Market[]>('/system/markets');await loadShops()}catch(e){contextError.value=e as Error}}
async function loadShops(){values.shopId='';shops.value=[];try{shops.value=await api<Shop[]>(`/system/shops?${query({marketCode:values.marketCode})}`)}catch(e){contextError.value=e as Error}}
async function load(){clearTimeout(timer);loading.value=true;error.value=null;try{const result=await api<Page<ImportTask>>(`/imports?${query({page:page.value,pageSize:20,sourceType:source.value,status:status.value})}`);tasks.value=result.items;total.value=result.total;if(alive&&tasks.value.some(t=>['CREATED','VALIDATING','IMPORTING','AGGREGATING'].includes(t.status)))timer=setTimeout(load,4000)}catch(e){error.value=e as Error}finally{loading.value=false}}
function choose(upload:UploadFile,uploadList:UploadFile[]){const message=validateFile(upload.raw);if(message){ElMessage.error(`${upload.name}: ${message}`);files.value=uploadList.filter(item=>item.uid!==upload.uid)}}
async function upload(force=false){if(!await form.value?.validate().catch(()=>false))return;const selected=files.value.flatMap(item=>item.raw?[item.raw]:[]);if(!selected.length){ElMessage.error('请选择至少一个文件');return}busy.value=true;try{const body=new FormData();Object.entries(values).forEach(([k,v])=>{if(v)body.append(k,v)});selected.forEach(item=>body.append('file',item));if(force)body.append('force','true');await api('/imports',{method:'POST',body});ElMessage.success(`已提交 ${selected.length} 个文件，处理结果请查看导入历史`);files.value=[];page.value=1;await load()}catch(e){if((e as any).code==='IMPORT_FILE_DUPLICATE'&&auth.isAdmin&&!force){try{await ElMessageBox.confirm('批量文件中有文件已经成功导入。确认强制重跑本批文件？系统仍会按业务唯一键更新数据。','文件已导入',{confirmButtonText:'强制重跑',cancelButtonText:'取消',type:'warning'});busy.value=false;await upload(true)}catch{/* User cancelled. */}}else ElMessage.error((e as Error).message)}finally{busy.value=false}}
async function details(task:ImportTask){selected.value=task;errorPage.value=1;drawer.value=true;await loadDetails()}
async function loadDetails(){if(!selected.value)return;detailBusy.value=true;detailError.value=null;try{selected.value=await api<ImportTask>(`/imports/${selected.value.id}`);const result=await api<Page<ImportError>>(`/imports/${selected.value.id}/errors?${query({page:errorPage.value,pageSize:20})}`);errors.value=result.items;errorTotal.value=result.total}catch(e){detailError.value=e as Error}finally{detailBusy.value=false}}
async function reaggregate(task:ImportTask){try{await ElMessageBox.confirm('将仅重新计算此任务涉及的日聚合数据。','确认聚合重算',{confirmButtonText:'开始重算',cancelButtonText:'取消'});await api(`/imports/${task.id}/reaggregate`,{method:'POST'});ElMessage.success('重算已提交');await load()}catch(e){if(e instanceof Error)ElMessage.error(e.message)}}
onMounted(()=>{void context();void load()});onBeforeUnmount(()=>{alive=false;clearTimeout(timer)})
</script>
<template>
<div class="page-head"><div><h1>数据导入</h1><p>上传 TikTok Shop 导出文件，更新店铺经营数据 · 版本 2026.09.07-product-period-v3</p></div></div>
<RequestError :error="contextError" @retry="context"/>
<section class="surface panel import-workspace"><div class="panel-head"><h2>导入工作区</h2><small class="muted">支持批量导入 XLSX / XLS · 单文件最大 100 MB · 文件数量不限制（单批总大小仍限 500 MB）</small></div><el-form ref="form" :model="values" label-position="top" @submit.prevent="upload()"><div class="import-fields"><el-form-item label="数据源" prop="sourceType" required><el-select v-model="values.sourceType"><el-option v-for="s in sources" :key="s.value" :value="s.value" :label="s.label"/></el-select></el-form-item><el-form-item label="市场" prop="marketCode" required><el-select v-model="values.marketCode" @change="loadShops"><el-option v-for="m in markets" :key="m.marketCode" :value="m.marketCode" :label="`${m.marketName} (${m.marketCode})`"/></el-select></el-form-item><el-form-item label="店铺" prop="shopId" :rules="[{required:true,message:'请选择店铺',trigger:'change'}]"><el-select v-model="values.shopId" placeholder="请选择店铺" filterable><el-option v-for="s in shops" :key="s.id" :value="s.id" :label="s.shopName"/></el-select></el-form-item><el-form-item label="业务日期" prop="bizDate"><el-date-picker v-model="values.bizDate" type="date" value-format="YYYY-MM-DD" placeholder="无日期信息的单日文件可指定" style="width:100%"/></el-form-item></div><el-upload v-model:file-list="files" :disabled="busy" drag :auto-upload="false" multiple accept=".xlsx,.xls" :on-change="choose"><el-icon class="upload-icon"><UploadFilled/></el-icon><div class="upload-title">将文件拖到这里，或 <span>选择文件</span></div><div class="muted small">可同时选择多个同类文件，系统会按当前数据源、市场和店铺排队处理</div></el-upload><div class="upload-footer"><small class="muted">历史商品报表可直接按周/月/任意导出区间导入，系统自动读取文件日期范围；不会把区间汇总错误拆到某一天。</small><el-button native-type="submit" type="primary" :loading="busy" :disabled="!files.length||!!contextError">开始批量导入</el-button></div></el-form></section>
<section class="surface table-panel"><div class="panel-head"><h2>导入历史 <small class="muted">{{ total }} 条记录</small></h2><el-button text aria-label="刷新导入历史" @click="load"><el-icon><Refresh/></el-icon></el-button></div><div class="actions history-filters"><el-select v-model="source" placeholder="全部数据源" clearable aria-label="筛选数据源" style="width:220px" @change="page=1;load()"><el-option v-for="s in sources" :key="s.value" :value="s.value" :label="s.label"/></el-select><el-select v-model="status" placeholder="全部状态" clearable aria-label="筛选导入状态" style="width:160px" @change="page=1;load()"><el-option v-for="s in states" :key="s" :value="s"><StatusBadge :status="s"/></el-option></el-select></div><RequestError :error="error" @retry="load"/><el-table v-loading="loading" :data="tasks" empty-text="暂无导入记录，请在上方上传文件"><el-table-column prop="originalFilename" label="文件" min-width="220" show-overflow-tooltip/><el-table-column label="数据源" min-width="170"><template #default="{row}">{{ sources.find(s=>s.value===row.sourceType)?.label??row.sourceType }}</template></el-table-column><el-table-column prop="marketCode" label="市场" width="70"/><el-table-column label="店铺" min-width="120" show-overflow-tooltip><template #default="{row}">{{ row.shopName??row.shopId }}</template></el-table-column><el-table-column label="业务日期范围" width="210"><template #default="{row}">{{ row.bizDateFrom ? (row.bizDateTo && row.bizDateTo!==row.bizDateFrom ? `${row.bizDateFrom} ~ ${row.bizDateTo}` : row.bizDateFrom) : '自动识别' }}</template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><StatusBadge :status="row.status"/></template></el-table-column><el-table-column label="数据量（成功/总数）" width="150" align="right"><template #default="{row}"><span class="number">{{ row.successRows }} / {{ row.totalRows }}</span></template></el-table-column><el-table-column prop="startedAt" label="开始时间" width="180"/><el-table-column prop="createdBy" label="操作者" width="110"/><el-table-column label="操作" fixed="right" width="150"><template #default="{row}"><el-button text type="primary" size="small" @click="details(row)">{{ row.status==='FAILED'?'错误详情':'详情' }}</el-button><el-button v-if="auth.isAdmin&&row.status==='AGGREGATE_FAILED'" text type="warning" size="small" @click="reaggregate(row)">重算</el-button></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="page" :page-size="20" :total="total" layout="total, prev, pager, next" @current-change="load"/></div></section>
<el-drawer v-model="drawer" title="导入任务详情" size="min(760px, 100vw)"><RequestError :error="detailError" @retry="loadDetails"/><div v-if="selected" v-loading="detailBusy" class="details"><el-descriptions :column="2" border><el-descriptions-item label="文件" :span="2">{{ selected.originalFilename }}</el-descriptions-item><el-descriptions-item label="状态"><StatusBadge :status="selected.status"/></el-descriptions-item><el-descriptions-item label="任务 ID">{{ selected.id }}</el-descriptions-item><el-descriptions-item label="成功行数">{{ selected.successRows }}</el-descriptions-item><el-descriptions-item label="失败行数">{{ selected.failedRows }}</el-descriptions-item><el-descriptions-item label="开始时间">{{ selected.startedAt }}</el-descriptions-item><el-descriptions-item label="结束时间">{{ selected.finishedAt??'—' }}</el-descriptions-item></el-descriptions><el-alert v-if="selected.errorMessage" type="error" :title="selected.errorMessage" :closable="false"/><h2>错误明细</h2><el-table :data="errors" empty-text="此任务暂无行级错误"><el-table-column prop="rowNo" label="行号" width="64"/><el-table-column prop="fieldName" label="字段" min-width="100"/><el-table-column prop="rawValue" label="原值" min-width="100" show-overflow-tooltip/><el-table-column prop="errorCode" label="错误码" min-width="140"/><el-table-column prop="message" label="说明" min-width="200"/></el-table><el-pagination v-model:current-page="errorPage" :total="errorTotal" :page-size="20" layout="prev, pager, next" @current-change="loadDetails"/></div></el-drawer>
</template>
<style scoped>
.import-workspace{margin-bottom:20px}.import-fields{display:grid;grid-template-columns:1.4fr 1fr 1.2fr 1.2fr;gap:16px}.upload-icon{font-size:32px;color:#667085;margin-bottom:8px}.upload-title{font-size:14px;margin-bottom:8px}.upload-title span{color:var(--hm-text);font-weight:600}.upload-footer{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-top:16px}.history-filters{margin-bottom:16px}
:deep(.el-upload-dragger){padding:24px;background:#fff;border:1px dashed #D9E1EA;border-radius:10px;transition:background 150ms,border-color 150ms,box-shadow 150ms}:deep(.el-upload-dragger:hover){background:#F8FBFD;border-color:var(--hm-accent);box-shadow:0 0 0 3px var(--hm-focus-ring)}
@media(max-width:1000px){.import-fields{grid-template-columns:1fr 1fr}}@media(max-width:600px){.import-fields{grid-template-columns:1fr;gap:0}.upload-footer{align-items:flex-start;flex-direction:column}.upload-footer .el-button{width:100%}}
</style>
