<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { api, query, save } from '../../api/client'
import type { DailyReport, DailyReportRow, DailyTask } from '../../api/types'
import { useAuth } from '../../stores/auth'
import RequestError from '../../components/RequestError.vue'

const auth=useAuth(), leader=computed(()=>auth.user?.roles.some(role=>['ADMIN','BOSS'].includes(role.roleCode))??false)
const localDate=()=>{const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`}
const selectedDate=ref(localDate()),reportDate=ref(localDate()),tab=ref(leader.value?'overview':'submit'),rows=ref<DailyReportRow[]>([]),loading=ref(false),saving=ref(false),error=ref<Error|null>(null)
const blankTask=():DailyTask=>({workModule:'',workDetail:'',planDelivery:'',actualResult:'',completionStatus:'进行中',issueNextStep:'',resultLink:''})
const report=reactive<DailyReport>({reportDate:reportDate.value,groupName:'',roleMarket:'',todayFocus:'',keyResult:'',needBossSupport:'',tomorrowFocus:'',submissionStatus:'DRAFT',reporterName:'',tasks:[blankTask()]})
const grouped=computed(()=>{
  const byReporter=new Map<string,DailyReportRow[]>();for(const row of rows.value){const key=`${row.reporterName}｜${row.groupName}｜${row.roleMarket}`;byReporter.set(key,[...(byReporter.get(key)??[]),row])}return [...byReporter.entries()]
})
function applyMine(value:DailyReport){const tasks=value.tasks.length===0?[blankTask()]:value.tasks.length===1?value.tasks:[{...blankTask(),workModule:value.tasks.map(task=>task.workModule).filter(Boolean).join('、'),workDetail:value.tasks.map(task=>task.workDetail).filter(Boolean).join('\n'),planDelivery:value.tasks.map(task=>task.planDelivery).filter(Boolean).join('\n'),actualResult:value.tasks.map(task=>task.actualResult).filter(Boolean).join('\n'),completionStatus:value.tasks.some(task=>task.completionStatus==='已阻塞')?'已阻塞':value.tasks.some(task=>task.completionStatus==='进行中')?'进行中':value.tasks.every(task=>task.completionStatus==='已完成')?'已完成':'未开始',issueNextStep:value.tasks.map(task=>task.issueNextStep).filter(Boolean).join('\n'),resultLink:value.tasks.map(task=>task.resultLink).filter(Boolean).join('\n')}];Object.assign(report,{...value,reportDate:reportDate.value,tasks:tasks.map(task=>({...task}))})}
async function loadRows(){loading.value=true;error.value=null;try{rows.value=await api<DailyReportRow[]>(`/daily-reports?${query({date:selectedDate.value})}`)}catch(e){error.value=e as Error}finally{loading.value=false}}
async function loadMine(){try{applyMine(await api<DailyReport>(`/daily-reports/mine?${query({date:reportDate.value})}`))}catch(e){error.value=e as Error}}
function payload(){return {groupName:report.groupName,roleMarket:report.roleMarket,todayFocus:report.todayFocus,keyResult:report.keyResult,needBossSupport:report.needBossSupport,tomorrowFocus:report.tomorrowFocus,tasks:report.tasks}}
async function store(submit:boolean){
  saving.value=true
  try{applyMine(await save<DailyReport>(submit?`/daily-reports/mine/${reportDate.value}/submit`:`/daily-reports/mine/${reportDate.value}`,payload(),submit?'POST':'PUT'));ElMessage.success(submit?'日报已提交':'日报已暂存');await loadRows()}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}
}
async function submit(){
  if(!report.groupName.trim()||!report.roleMarket.trim())return ElMessage.error('请填写所属小组和岗位 / 负责市场')
  if(report.tasks.some(task=>!task.workModule.trim()||!task.workDetail.trim()||!task.planDelivery.trim()))return ElMessage.error('请填写每项任务的工作模块、今日具体工作和计划交付')
  await store(true)
}
watch(reportDate,()=>void loadMine())
watch(selectedDate,()=>void loadRows())
onMounted(()=>{void Promise.all([loadRows(),loadMine()])})
</script>

<template>
  <div class="page-head"><div><h1>日报</h1><p>{{ leader?'老板可按日报标签查看全员记录，也可提交自己的日报。':'提交并查看仅属于自己账号的日报记录。' }}</p></div></div>
  <el-tabs v-model="tab" class="sheet-tabs">
    <el-tab-pane v-if="leader" label="老板日报" name="overview">
      <section class="surface excel-sheet"><div class="excel-title">TikTok 团队｜每日工作汇报</div><div class="excel-note">老板先看本页；具体到个人的工作请查看“团队每日明细”。</div>
        <div class="date-bar"><label>日期<el-date-picker v-model="selectedDate" value-format="YYYY-MM-DD" type="date" :clearable="false"/></label><span>{{ rows.length }} 项已上报工作</span></div>
        <RequestError :error="error" @retry="loadRows"/>
        <div v-loading="loading" class="report-cards"><article v-for="[name,tasks] in grouped" :key="name" class="report-card"><header><strong>汇报人：{{ tasks[0].reporterName }}</strong><span>今日重点：{{ tasks[0].todayFocus||'—' }}</span></header><div class="table-scroll"><table><thead><tr><th>工作归属</th><th>负责人 / 成员</th><th>工作模块</th><th>今日具体工作</th><th>计划交付</th><th>实际完成 / 结果</th><th>完成状态</th><th>问题及下一步</th></tr></thead><tbody><tr v-for="task in tasks" :key="task.taskId"><td>{{ task.groupName }}</td><td>{{ task.reporterName }}</td><td>{{ task.workModule }}</td><td>{{ task.workDetail }}</td><td>{{ task.planDelivery }}</td><td>{{ task.actualResult||'—' }}</td><td><el-tag size="small" :type="task.completionStatus==='已完成'?'success':task.completionStatus==='已阻塞'?'danger':'warning'">{{ task.completionStatus }}</el-tag></td><td>{{ task.issueNextStep||'—' }}</td></tr></tbody></table></div><div class="boss-summary"><span><b>今日最重要成果</b>{{ tasks[0].keyResult||'—' }}</span><span><b>需老板支持</b>{{ tasks[0].needBossSupport||'—' }}</span><span><b>明日重点</b>{{ tasks[0].tomorrowFocus||'—' }}</span></div></article><el-empty v-if="!loading&&!grouped.length" description="该日期暂无日报"/></div>
      </section>
    </el-tab-pane>
    <el-tab-pane :label="leader?'团队每日明细':'我的日报记录'" name="details">
      <section class="surface excel-sheet"><div class="excel-title">TikTok 团队｜个人每日工作明细</div><div class="excel-note">每人每天一行完整日报；成员只能读取自己的记录。</div>
        <div class="date-bar"><label>日期<el-date-picker v-model="selectedDate" value-format="YYYY-MM-DD" type="date" :clearable="false"/></label><span>{{ leader?'全员记录':'仅我的记录' }}</span></div>
        <RequestError :error="error" @retry="loadRows"/>
        <div class="table-scroll"><el-table v-loading="loading" :data="rows" border empty-text="该日期暂无日报"><el-table-column prop="reportDate" label="日期" width="110"/><el-table-column prop="groupName" label="所属小组" min-width="115"/><el-table-column prop="reporterName" label="负责人" min-width="105"/><el-table-column prop="roleMarket" label="岗位 / 负责市场" min-width="150"/><el-table-column prop="workDetail" label="今日具体工作" min-width="210" show-overflow-tooltip/><el-table-column prop="planDelivery" label="计划交付" min-width="165" show-overflow-tooltip/><el-table-column prop="actualResult" label="实际完成 / 结果" min-width="180" show-overflow-tooltip/><el-table-column label="完成状态" width="105"><template #default="{row}"><el-tag size="small" :type="row.completionStatus==='已完成'?'success':row.completionStatus==='已阻塞'?'danger':'warning'">{{ row.completionStatus }}</el-tag></template></el-table-column><el-table-column prop="issueNextStep" label="问题及下一步" min-width="190" show-overflow-tooltip/><el-table-column label="成果链接 / 位置" min-width="145"><template #default="{row}"><a v-if="row.resultLink" :href="row.resultLink" target="_blank" rel="noopener">查看成果</a><span v-else>—</span></template></el-table-column></el-table></div>
      </section>
    </el-tab-pane>
    <el-tab-pane label="提交日报" name="submit">
      <section class="surface submit-sheet"><div class="excel-title">TikTok 团队｜个人每日工作明细</div><p class="excel-note">早上写计划，收工前补结果。暂存仅本人可见，提交后领导看到完全相同的字段。</p>
        <div class="report-meta"><label>日期<el-date-picker v-model="reportDate" value-format="YYYY-MM-DD" type="date" :clearable="false"/></label><label>所属小组<el-input v-model="report.groupName" maxlength="100" placeholder="如：视频组"/></label><label>负责人<el-input :model-value="report.reporterName" readonly/></label><label>岗位 / 负责市场<el-input v-model="report.roleMarket" maxlength="100" placeholder="如：马来西亚编导"/></label><label class="wide">今日重点<el-input v-model="report.todayFocus" type="textarea" :rows="2" maxlength="2000" show-word-limit placeholder="写清当天最重要的工作重点"/></label></div>
        <div class="task-head"><h2>日报明细</h2><span class="muted small">每人每天填写一份完整日报</span></div>
        <article v-if="report.tasks[0]" class="task-form"><div class="task-form-title"><strong>今日工作汇总</strong></div><div class="task-grid"><label>工作模块<el-input v-model="report.tasks[0].workModule" maxlength="100" placeholder="如：内容审核、素材制作"/></label><label>完成状态<el-select v-model="report.tasks[0].completionStatus"><el-option label="未开始" value="未开始"/><el-option label="进行中" value="进行中"/><el-option label="已完成" value="已完成"/><el-option label="已阻塞" value="已阻塞"/></el-select></label><label class="wide">今日具体工作<el-input v-model="report.tasks[0].workDetail" type="textarea" :rows="5" maxlength="2000" show-word-limit placeholder="请把今天的工作一次性写完整，可分行描述多个事项"/></label><label>计划交付<el-input v-model="report.tasks[0].planDelivery" type="textarea" :rows="3" maxlength="2000" show-word-limit placeholder="如：脚本 5 条、素材 3 组"/></label><label>实际完成 / 结果<el-input v-model="report.tasks[0].actualResult" type="textarea" :rows="3" maxlength="2000" show-word-limit/></label><label>成果链接 / 位置<el-input v-model="report.tasks[0].resultLink" maxlength="2000" placeholder="链接或文件夹位置（可选）"/></label><label class="wide">问题及下一步<el-input v-model="report.tasks[0].issueNextStep" type="textarea" :rows="3" maxlength="2000" show-word-limit placeholder="可一次性写明问题、处理人和时间"/></label></div></article>
        <div class="summary-form"><label>今日最重要成果<el-input v-model="report.keyResult" type="textarea" :rows="2" maxlength="2000" show-word-limit/></label><label>需老板支持<el-input v-model="report.needBossSupport" type="textarea" :rows="2" maxlength="2000" show-word-limit/></label><label>明日重点<el-input v-model="report.tomorrowFocus" type="textarea" :rows="2" maxlength="2000" show-word-limit/></label></div>
        <div class="submit-bar"><span>{{ report.submissionStatus==='SUBMITTED'?'该日报已提交，继续编辑后可再次提交。':'成员暂存的日报仅本人可见。' }}</span><div class="actions"><el-button :loading="saving" @click="store(false)">暂存日报</el-button><el-button type="primary" :loading="saving" @click="submit">提交日报</el-button></div></div>
      </section>
    </el-tab-pane>
  </el-tabs>
</template>

<style scoped>
.sheet-tabs{margin-top:-8px}.excel-sheet,.submit-sheet{overflow:hidden}.sheet-tabs :deep(.el-tabs__item){height:42px;color:var(--hm-text-secondary)}.sheet-tabs :deep(.el-tabs__item.is-active){color:var(--hm-text)}.sheet-tabs :deep(.el-tabs__active-bar){height:2px;background:var(--hm-accent)}.excel-title{padding:16px 20px;background:var(--hm-bg-soft);color:var(--hm-text);font-size:16px;font-weight:650;text-align:center;border-bottom:1px solid var(--hm-border)}.excel-note{padding:10px 16px;color:var(--hm-text-secondary);background:#FAFBFD;border-bottom:1px solid var(--hm-border);font-size:12px}.date-bar{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 16px;color:var(--hm-text-secondary);font-size:12px}.date-bar label,.report-meta label,.task-grid label,.summary-form label{display:grid;gap:6px;color:#475467;font-size:12px}.date-bar label{grid-template-columns:auto 148px;align-items:center}.report-cards{display:grid;gap:14px;padding:0 16px 16px}.report-card{border:1px solid var(--hm-border);border-radius:10px;overflow:hidden}.report-card header{padding:10px 12px;background:var(--hm-bg-soft);display:flex;gap:10px;align-items:center}.report-card header span{color:var(--hm-text-secondary);font-size:12px}table{border-collapse:collapse;width:100%;min-width:1100px;font-size:12px}th{background:var(--hm-bg-soft);color:#475467;font-weight:650;text-align:left}th,td{padding:10px;border:1px solid var(--hm-border);vertical-align:top;line-height:1.55;white-space:pre-wrap}.boss-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border-top:1px solid var(--hm-border);background:#FAFBFD}.boss-summary span{padding:10px;border-right:1px solid var(--hm-border);font-size:12px;white-space:pre-wrap}.boss-summary span:last-child{border-right:0}.boss-summary b{display:block;color:var(--hm-text);margin-bottom:4px}.submit-sheet{padding-bottom:0}.submit-sheet .excel-note{margin:0}.report-meta{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;padding:18px;border-bottom:1px solid var(--hm-border)}.task-head{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:18px}.task-form{margin:0 18px 16px;border:1px solid var(--hm-border);border-radius:10px;overflow:hidden}.task-form-title{padding:10px 12px;background:var(--hm-bg-soft);display:flex;justify-content:space-between;align-items:center}.task-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;padding:14px}.summary-form{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;padding:2px 18px 18px}.wide{grid-column:1/-1}.submit-bar{display:flex;justify-content:space-between;align-items:center;gap:14px;padding:16px 18px;background:var(--hm-bg-soft);border-top:1px solid var(--hm-border);color:var(--hm-text-secondary);font-size:12px}
@media(max-width:850px){.report-meta{grid-template-columns:repeat(2,minmax(0,1fr))}.summary-form,.boss-summary{grid-template-columns:1fr}.boss-summary span{border-right:0;border-bottom:1px solid var(--hm-border)}.boss-summary span:last-child{border-bottom:0}}
@media(max-width:600px){.date-bar,.submit-bar{align-items:stretch;flex-direction:column}.date-bar label{grid-template-columns:1fr}.report-meta,.task-grid,.summary-form{grid-template-columns:1fr}.wide{grid-column:auto}.task-form{margin:0 12px 12px}}
</style>
